services:
  db:
    image: postgres:16-alpine
    container_name: student_projects_db
    restart: unless-stopped
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: student123
      POSTGRES_DB: student_projects
      POSTGRES_HOST_AUTH_METHOD: md5
      POSTGRES_INITDB_ARGS: '--auth-host=md5'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
